### PR TITLE
monitoring: add dashboard and alerts sections, example dashboard and …

### PR DESCRIPTION
**Pull request by naseemkullah**
…alert

Provide sample dashboard and sample alert to get users started with monitoring Fluent Bit.

Signed-off-by: Naseem <naseem@transit.app>

cc @PettitWesley

### CODE REVIEW

**Comment by edsiper** [comment]
@PettitWesley can u take a look ?

**Comment by PettitWesley** [comment]
@edsiper approved

**Comment by naseemkullah** [comment]
bump

**Comment by naseemkullah** [comment]
@edsiper @PettitWesley I think we need higher velocity in getting these doc PRs in in order to encourage users to continue updating them.

**Pull request merged**
