### PR TITLE
administration: update unsupported yaml config features

### LINKED ISSUE #1247: YAML support documentation clarifications
As per the Slack discussion: https://fluent-all.slack.com/archives/C0CTQGHKJ/p1698837217729209

Support for YAML configurations is not yet a 1:1 match to the classic configuration method using conf files.
I believe it would be helpful to clarify which parts are not yet available, and update the documentation accordingly, while these new features are being worked on.

Features not yet compatible:
- Custom parsers section
- Multiple parsers support under `service.parser_file`

### PR DESCRIPTION
**Pull request by Rezrazi**
closes #1247

### CODE REVIEW

**Comment by patrick-stephens** [comment]
Please handle the DCO failure as we cannot merge without it.

**Comment by Rezrazi** [comment]
@patrick-stephens fixed 👌

**Review by pwhelan — APPROVED** [review]
This is accurate. The documentation should be updated once the functionality makes it into fluent-bit.

**Comment by lecaros** [comment]
Merged. Thanks for your contribution @Rezrazi!

**Pull request merged**
