### PR TITLE
Azure Kusto Output Plugin Docs

### PR DESCRIPTION
**Pull request by papigers**
Documentation for the new [Kusto output plugin](https://github.com/fluent/fluent-bit/pull/5645)

### CODE REVIEW

**Comment by papigers** [comment]
@patrick-stephens just a reminder now that the plugin PR is merged :)

**Comment by patrick-stephens** [comment]
Yeah, we cannot merge docs until the release though - otherwise it confuses people when they see docs for something only on a `master` build.

**Comment by patrick-stephens** [comment]
@lecaros not sure how we tag waiting for release or should this merge to master in advance of 2.0?

**Comment by lecaros** [comment]
We'll be branching by EOW. After that, all the PRs will go to 2.0. Meanwhile, you can tag them using the label 2.0.
Thanks!

**Comment by lecaros** [comment]
Thanks @papigers! I've merged the changes.

**Pull request merged**
