### PR TITLE
Update tail.md

### PR DESCRIPTION
**Pull request by AkshayDubey29**

### CODE REVIEW

**Comment by AkshayDubey29** [comment]
Wait for this to get merged, seems we may require few other options as well, it shouldn't be Boolean.

**Comment by nokute78** [comment]
@AkshayDubey29 Could you update this PR?
https://github.com/fluent/fluent-bit/pull/3239 is to support new parameter `db.journal_mode` and remove `db.wal`.

- Fix conflicts
- Replace `db.wal`  with `db.journal_mode`
- Add `DB.journal_mode` description at Configuration Parameters section
- Remove `DB.wal` from Configuration Parameters section

**Comment by AkshayDubey29** [comment]
@nokute78 Can you check?

**Comment by nokute78** [comment]
@AkshayDubey29 Thank you for quick response !
The documentation is good to me.

However, CI reports DCO error. [Latest commit](https://github.com/fluent/fluent-bit-docs/pull/492/commits/723f0fa07e97fa52c970727dce4e174853a93c42) is not signed off.

Can you fix it ?

**Comment by AkshayDubey29** [comment]
@nokute78 Done :-)

**Comment by nokute78** [comment]
@AkshayDubey29 Thank you.

@edsiper @agup006 Any comments?

**Comment by AkshayDubey29** [comment]
That's okay @agup006 :-)

**Pull request merged**
