### PR TITLE
out_forward: add 'unix_path' property

### PR DESCRIPTION
**Pull request by nokute78**
This PR is for https://github.com/fluent/fluent-bit/pull/4715 .

### CODE REVIEW

**Comment by nokute78** [comment]
I fixed conflict.

**Comment by nokute78** [comment]
https://github.com/fluent/fluent-bit/pull/4715 was merged to master.

**Comment by nokute78** [comment]
@lecaros ping. I fixed.

**Comment by lecaros** [comment]
Thanks @nokute78! I've merged it

**Pull request merged**
