### PR TITLE
out_cloudwatch_logs: add log_retention_days option

### PR DESCRIPTION
**Pull request by shogo82148**
a new property `log_retention_days` is introduced by https://github.com/fluent/fluent-bit/pull/2739

Addresses https://github.com/fluent/fluent-bit/issues/2691

CC: @PettitWesley

### CODE REVIEW

**Review by PettitWesley — APPROVED** [review]

**Comment by PettitWesley** [comment]
This should be merged after: https://github.com/fluent/fluent-bit/pull/2739

**Comment by PettitWesley** [comment]
@edsiper Please merge this was released

**Comment by shogo82148** [comment]
I resolved the conflicts, and it looks that this is already released as v1.7.0

https://github.com/fluent/fluent-bit/commit/69f66c249339ca231a1665e99971d9f1edd1b0c4

image

Please merge

**Comment by edsiper** [comment]
thanks

**Pull request merged**
