### PR TITLE
Dynatrace guide for http plugin

### PR DESCRIPTION
**Pull request by hans-lougas-dt**
This commit introduces a new page for Dynatrace output based on http plugin.
It provides sample configuration and recommended steps and additional resources to enable Fluent Bit output for Dynatrace http endpoint.

### CODE REVIEW

**Review by lecaros — CHANGES_REQUESTED** [review]
Hello @hans-lougas-dt,
you need to add the page to the SUMMARY.md file. Otherwise, it won't be visible in the docs site.

**Comment by hans-lougas-dt** [comment]
Thanks @lecaros , added it to SUMMARY.md

**Review by lecaros — APPROVED** [review]

**Comment by lecaros** [comment]
Merged! Thanks for your contribution @hans-lougas-dt!

**Comment by robertjahn** [comment]
Hi @lecaros - when might this merged change be reflected @ https://docs.fluentbit.io/manual/pipeline/outputs ?

**Comment by lecaros** [comment]
Hi @robertjahn,
We're currently merging for 3.2. Anything needed for current needs a PR. Having said that, you can submit a PR for 3.1 or we could try to do it as time permits.

**Pull request merged**
