### PR TITLE
Very minor grammar correction

### PR DESCRIPTION
**Pull request by kishaningithub**

### CODE REVIEW

**Comment by kishaningithub** [comment]
Can anyone explain what is this DCO bot trying to enforce? I am definitely not getting it.

Note - Above i have pushed a "Verified" commit and DCO is failing

**Comment by edsiper** [comment]
@kishaningithub 

when commiting, you have to use the option `-s` to sign-off the commits, e.g:

```
git commit -a -s -m "something..."
```

**Comment by kishaningithub** [comment]
I will do that @edsiper Just curious to know why such a level if security is needed for changes to documentation. If you can point me to any documentation it would be great.

**Comment by kishaningithub** [comment]
Have updated the commit @edsiper 

Also i think i have figured out the answer to my above question, to the future readers..
I got confused with "Sign Off" and "Sign"

- "Sign off" means that you comply with https://developercertificate.org/ This adds a "Signed-off-by" text inside the commit message
- "Sign" means you cryptographically authorize that the change was done by you and no-one else. This is achieved by the use of gpg keys

This repo only requires "Sign Off" which is reasonable

**Comment by lecaros** [comment]
Thanks for your contribution!

**Pull request merged**
