### PR TITLE
Azure Data Explorer docs leftovers

### PR DESCRIPTION
**Pull request by papigers**
Following #841 

Signed-off-by: Gershon Papi <papigers93@gmail.com>

### CODE REVIEW

**Comment by papigers** [comment]
@patrick-stephens @lecaros FYI

**Comment by patrick-stephens** [comment]
Looks fine to me but I'm going to await @lecaros as he knows what is going on with the 2.0 release and branching here so don't want to merge too soon.

**Review by patrick-stephens — APPROVED** [review]

**Comment by papigers** [comment]
@lecaros The new plugin's page is currently missing from the 2.0 doc site.
This PR should fix that, right? Anything I'm missing?

**Comment by papigers** [comment]
@patrick-stephens any chance you could help with bringing attention to this?

**Comment by patrick-stephens** [comment]
I'll ping @lecaros, everyone is heads down for the 2.0 release plus it's conference & holiday season so that's likely why some of the docs PRs for 2.0 are taking a while. Is this in 1.9 btw @papigers or just 2.0, I can't remember? 2.0 is not out yet so I don't think this will be merged until it is but if it needs a 1.9 update then we can.

**Comment by papigers** [comment]
It's for 2.0 but it's currently missing from the docs preview page for version 2.0 (https://docs.fluentbit.io/manual/v/2.0-pre/).

Sorry for nudging, just didn't want for this to go unnoticed.

**Comment by lecaros** [comment]
Hi @papigers, thanks for your contribution. Sorry for our delay on this. I've merged it.
Appreciate you taking the time to push this.

**Pull request merged**
