### PR TITLE
out_s3: make option auto_retry_requests default to be true

### PR DESCRIPTION
**Pull request by zhonghui12**
Doc update for PR: https://github.com/fluent/fluent-bit/pull/4213

Signed-off-by: Zhonghui Hu <zh0512xx@gmail.com>

### CODE REVIEW

**Comment by zhonghui12** [comment]
Don't merge this PR until Fluent Bit 1.9 is out.

**Review by PettitWesley — APPROVED** [review]

**Comment by PettitWesley** [comment]
We will wait to merge this until v1.9.0 comes out.

**Comment by lecaros** [comment]
Hi @PettitWesley, would you mind reviewing the conflict?
Thanks

**Comment by zhonghui12** [comment]
Hi @lecaros, the conflict should be resolved now

**Comment by lecaros** [comment]
hi @zhonghui12, thanks for your contribution!

**Comment by PettitWesley** [comment]
@lecaros @zhonghui12 I believe this feature is unreleased, it was only merged to fluent-bit master for 1.9

**Comment by lecaros** [comment]
@PettitWesley yes, this is for 1.9. Current merges in the master branch are for 1.9.

**Pull request merged**
