### PR TITLE
Adding a documentation page for Datadog

### PR DESCRIPTION
**Pull request by apigirl**
This is a new page in the output section to support the upcoming release of the Datadog integration.

### CODE REVIEW

**Comment by edsiper** [comment]
@apigirl thanks for your contribution!

I would like to ask for some quick changes:

- Please list this .md file in the SUMMARY.md file located at the root directory, otherwise it won't be rendered by the docs system.
- In the properties table (config), would you please specify if the options are mandatory or optional ?, we need to make sure new datadog users understand what to fill and why.

**Comment by edsiper** [comment]
ah, please sign-off your commits with "git commit -s ..."

**Comment by apigirl** [comment]
@edsiper - updates made - thanks for the feedback!

**Comment by apigirl** [comment]
@edsiper - I just got a final review + approval on this on my side, so I think we're good to merge!

**Comment by edsiper** [comment]
thanks!

**Comment by apigirl** [comment]
@eagletmt - thanks for merging! I am not seeing this on the docs site yet - did I miss adding it somewhere in the site, or does it need rebuilt?

**Comment by edsiper** [comment]
@apigirl changes will be published once v1.3 get released.

**Pull request merged**
