### PR TITLE
parsers_regex: fix broken links

### PR DESCRIPTION
**Pull request by SanyaKochhar**
Signed-off-by: Sanya Kochhar <kochhars@microsoft.com>

### CODE REVIEW

**Comment by nokute78** [comment]
Your patch is to link a specific commit https://github.com/fluent/fluent-bit-docs/tree/1787fd8bfb2035bf10faf8cb7b14c4521e1265b3.
So, if tail.md will be updated and the commit hash will be changed, the document will remain linking old tail.md.

How about fix like relative link? e.g. `../inputs/tail.md`

**Comment by SanyaKochhar** [comment]
@nokute78 yep, that makes sense, updated to relative links. Wasn't sure if this pointed to a specific commit on purpose before for versioning docs or something

**Comment by SanyaKochhar** [comment]
@edsiper could I get a review on this?

**Comment by edsiper** [comment]
Thanks!

**Pull request merged**
