### PR TITLE
Macos homebrew

### PR DESCRIPTION
**Pull request by matschaffer-roblox**
Adds homebrew instructions to the macOS section of the getting started page.

While I can see that @chenrui333's homebrew this isn't an "offical" package, it's been working great for me.

I'd like to be able to recommend it to new users of fluent-bit as well.

Note: this also replaces a few remaining "MacOS" usages with the more modern "macOS" used in the majority of the documentation.

### CODE REVIEW

**Comment by patrick-stephens** [comment]
Looks good @matschaffer-roblox , could you just prefix your commit messages with `macos: `?
https://github.com/fluent/fluent-bit-docs/blob/master/CONTRIBUTING.md#commit-subjects

**Comment by matschaffer-roblox** [comment]
@patrick-stephens done! Thanks for the review.

**Review by patrick-stephens — APPROVED** [review]

**Comment by patrick-stephens** [comment]
We do actually build macOS packages now automatically but we just don't push them to release servers.

**Comment by patrick-stephens** [comment]
Official implies support and the dev environment can be "challenging" so it would be great to have some contributors to help support it. I'm happy to push the release packages out potentially but they need some testing if you're happy to?

Probably not the best place to discuss this here though, do you want to raise an issue on the FB repo and we can continue there? The packages should appear on https://fluentbit-staging.s3.amazonaws.com/ but I'm struggling to find them even though the 2.0.6 staging job says they were uploaded - it may be because the 1.9.10 staging was after.

There are packages on the nightly builds though: 
- https://github.com/fluent/fluent-bit/suites/9739999362/artifacts/467527356
- https://github.com/fluent/fluent-bit/actions/runs/3645742948

**Pull request merged**
