### PR TITLE
out_s3: added data ordering preservation documentation

### PR DESCRIPTION
**Pull request by StephenLeeY**
Signed-off-by: Stephen Lee <sleemamz@amazon.com>

### CODE REVIEW

**Comment by edsiper** [comment]
@StephenLeeY pls fix the current conflicts so we can merge the PR

**Comment by edsiper** [comment]
@PettitWesley ping

**Comment by PettitWesley** [comment]
@edsiper I'll open a new PR for this

**Comment by PettitWesley** [comment]
@edsiper Actually I am closing this, these docs were already committed: https://github.com/fluent/fluent-bit-docs/blob/master/pipeline/outputs/s3.md

**Pull request closed without merging**
